when it's test failure reproduction run read a specified json file and rerun a list of module for specified browser.
choheekim/ember-exam pull request #6
Opened 2018-09-08 00:57 UTC by choheekim

2018-09-10 18:32 UTC, dcombslinkedin commented on lib/commands/exam.js
> +   * Adds an object which maps a list of module from browser id to config
list of modules, not list of module.

2018-09-10 18:33 UTC, dcombslinkedin commented on lib/commands/exam.js
> +      throw new Error(err);
I'm not sure I'd directly throw this error. I might wrap it in an error that says something like "error reading replay execution JSON file", then the error string from this error. It's clearer to the user that way.

2018-09-10 18:34 UTC, dcombslinkedin commented on lib/commands/exam.js
> +        const listOfModule = testMappingObj[browserId];
listOfModules, not listOfModule

2018-09-10 18:35 UTC, dcombslinkedin commented on lib/commands/exam.js
> +          throw Error ('browser id doesn\t exist in the file.');
ID, not id. Also, the error message needs to be more clear about what it means, like 'the file' should really say which file it's talking about, and 'browser id', should be replaced with something saying what the ID is you're looking for (presumably it was specified by the caller?)

2018-09-10 18:36 UTC, dcombslinkedin commented on lib/commands/exam.js
> +      const browserId = (() => {
Same comment as in the other file - you don't really need a function for this, do you?

2018-09-10 18:37 UTC, dcombslinkedin commented on lib/commands/exam.js
>        const fileName = 'test-execution-%TIMESTAMP%.json'.replace('%TIMESTAMP%', Date.now());
Same comment as other file:    fileName = `test-execution-${Date.now()}.json`;

2018-09-10 18:38 UTC, dcombslinkedin requested changes
minor stylistic issues, but otherwise okay.

2018-09-20 22:56 UTC, scalvert commented
Can we open these against `ember-cli/ember-exam` instead of this repo. It's going to be more work/time to PR against this repo, then have to PR again against upstream. Additionally, we want to get eyes on this code as early as possible. 

I'd suggest we be very explicit, in the PR description for _all_ the PRs that are related, what the sequence is for landing these changes.

For example - possible PR titles and description:

Title: [Part 1] - Load balancing Ember Exam - add weighted option
Description: Adds weighted option to ember exam to provide better utilization of browser parallelization.

This change is Part 1 in a 5 part series:
- Part 1 - add weighted option
- Part 2 - do something else
- Part 3 - do the part 3 thing
- etc.

2019-03-27 16:12 UTC, closed without merging